export const userInputs = [
  {
    name: "email",
    id: 1,
    label: "אימייל",
    type: "mail",
    placeholder: "john_doe@gmail.com",
  },
  {
    name: "l_name",
    id: 2,
    label: "שם משפחה",
    type: "text",
    placeholder: "John Doe",
  },
  {
    name: "f_name",
    id: 3,
    label: "שם פרטי",
    type: "text",
    placeholder: "john_doe",
  },
  {
    name: "phone",
    id: 3,
    label: "טלפון",
    type: "number",
    placeholder: "+1 234 567 89",
  },
  {
    name: "address",
    id: 3,
    label: "כתובת",
    type: "text",
    placeholder: "כתובת",
  },
  {
    name: "city",
    id: 3,
    label: "עיר",
    type: "text",
    placeholder: "עיר",
  },
  {
    name: "cash",
    id: 4,
    label: "עובר ושב",
    type: "number",
    placeholder: "+1 234 567 89",
  },
  {
    name: "credit",
    id: 5,
    label: "קרדיט",
    type: "number",
  },
  {
    name: "account",
    id: 6,
    label: "חשבונות",
    type: "number",
    placeholder: "Elton St. 216 NewYork",
  },
  {
    name: "personal_id",
    id: 7,
    label: "תז",
    type: "number",
    placeholder: "USA",
  },
];

export const accountsInputs = [
  {
    id: 1,
    name: "accountNum",
    label: "מס חשבון",
    type: "number",
    // placeholder: "Apple Macbook Pro",
  },
  {
    name: "cash",
    id: 2,
    label: "עובר ושב",
    type: "number",
    // placeholder: "+1 234 567 89",
  },
  {
    name: "credit",
    id: 3,
    label: "קרדיט",
    type: "number",
  },
  {
    id: 4,
    name: "minusInterest",
    label: "ריבית",
    type: "number",
    // placeholder: "100",
  },
];
